package erpsolfms.erpsolfmsmodel.erpsolfmsvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 08 14:38:30 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArNoteDetailViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ArNoteDetailViewImpl() {
    }
}

