package erpsolfms.erpsolfmsmodel.erpsolfmsvo;

import erpsolfms.erpsolfmsmodel.erpsolfmseo.ArNoteMasterImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 07 15:16:05 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArNoteMasterViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_ARNOTEMASTER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NoteCode,
        Customerid,
        Deptid,
        Companyid,
        DocTypeId,
        Locationid,
        EntryDate,
        TotalAmount,
        RefVoucher,
        Submit,
        PostToIntFace,
        PostToGl,
        Createdby,
        Modifiedby,
        CreatedDate,
        ModifiedDate,
        SubmitBy,
        GlvoucherNo,
        ArPosted,
        Salespersonid,
        Pid,
        Remarks,
        RemarksNarr,
        FromSaleDate,
        ToSaleDate,
        DiscountType,
        AuditorCheck,
        AuditRemarks,
        RefSalesorderid,
        RefDoctypeid,
        RefVoucherNo,
        IsMigrated,
        MigratedDate,
        DocDate,
        LocCurrcode,
        ExchangeRate,
        FcurrTotalAmount,
        Notemasterseq,
        txtCustomerName,
        txtSalesPersonName,
        ArNoteDetailView,
        AllCustomersView,
        SoSalesPersonsView,
        AccAllCustomersView,
        AccSoSalesPersonsView,
        AccSoSalesPersonsDefaultVC;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int NOTECODE = AttributesEnum.NoteCode.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int ENTRYDATE = AttributesEnum.EntryDate.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int REFVOUCHER = AttributesEnum.RefVoucher.index();
    public static final int SUBMIT = AttributesEnum.Submit.index();
    public static final int POSTTOINTFACE = AttributesEnum.PostToIntFace.index();
    public static final int POSTTOGL = AttributesEnum.PostToGl.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int SUBMITBY = AttributesEnum.SubmitBy.index();
    public static final int GLVOUCHERNO = AttributesEnum.GlvoucherNo.index();
    public static final int ARPOSTED = AttributesEnum.ArPosted.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int PID = AttributesEnum.Pid.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REMARKSNARR = AttributesEnum.RemarksNarr.index();
    public static final int FROMSALEDATE = AttributesEnum.FromSaleDate.index();
    public static final int TOSALEDATE = AttributesEnum.ToSaleDate.index();
    public static final int DISCOUNTTYPE = AttributesEnum.DiscountType.index();
    public static final int AUDITORCHECK = AttributesEnum.AuditorCheck.index();
    public static final int AUDITREMARKS = AttributesEnum.AuditRemarks.index();
    public static final int REFSALESORDERID = AttributesEnum.RefSalesorderid.index();
    public static final int REFDOCTYPEID = AttributesEnum.RefDoctypeid.index();
    public static final int REFVOUCHERNO = AttributesEnum.RefVoucherNo.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int FCURRTOTALAMOUNT = AttributesEnum.FcurrTotalAmount.index();
    public static final int NOTEMASTERSEQ = AttributesEnum.Notemasterseq.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalesPersonName.index();
    public static final int ARNOTEDETAILVIEW = AttributesEnum.ArNoteDetailView.index();
    public static final int ALLCUSTOMERSVIEW = AttributesEnum.AllCustomersView.index();
    public static final int SOSALESPERSONSVIEW = AttributesEnum.SoSalesPersonsView.index();
    public static final int ACCALLCUSTOMERSVIEW = AttributesEnum.AccAllCustomersView.index();
    public static final int ACCSOSALESPERSONSVIEW = AttributesEnum.AccSoSalesPersonsView.index();
    public static final int ACCSOSALESPERSONSDEFAULTVC = AttributesEnum.AccSoSalesPersonsDefaultVC.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ArNoteMasterViewRowImpl() {
    }

    /**
     * Gets ArNoteMaster entity object.
     * @return the ArNoteMaster
     */
    public ArNoteMasterImpl getArNoteMaster() {
        return (ArNoteMasterImpl) getEntity(ENTITY_ARNOTEMASTER);
    }

    /**
     * Gets the attribute value for NOTE_CODE using the alias name NoteCode.
     * @return the NOTE_CODE
     */
    public String getNoteCode() {
        return (String) getAttributeInternal(NOTECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTE_CODE using the alias name NoteCode.
     * @param value value to set the NOTE_CODE
     */
    public void setNoteCode(String value) {
        setAttributeInternal(NOTECODE, value);
    }

    /**
     * Gets the attribute value for CUSTOMERID using the alias name Customerid.
     * @return the CUSTOMERID
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMERID using the alias name Customerid.
     * @param value value to set the CUSTOMERID
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
        try {
            getAccSoSalesPersonsDefaultVC().setNamedWhereClauseParam("P_ADF_CUSTOMERID", value);
            getAccSoSalesPersonsDefaultVC().executeQuery();
            setSalespersonid((String) getAccSoSalesPersonsDefaultVC().first().getAttribute("Salespersonid"));
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }        
    }

    /**
     * Gets the attribute value for DEPTID using the alias name Deptid.
     * @return the DEPTID
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTID using the alias name Deptid.
     * @param value value to set the DEPTID
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @return the DOC_TYPE_ID
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @param value value to set the DOC_TYPE_ID
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for ENTRY_DATE using the alias name EntryDate.
     * @return the ENTRY_DATE
     */
    public Date getEntryDate() {
        return (Date) getAttributeInternal(ENTRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTRY_DATE using the alias name EntryDate.
     * @param value value to set the ENTRY_DATE
     */
    public void setEntryDate(Date value) {
        setAttributeInternal(ENTRYDATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for REF_VOUCHER using the alias name RefVoucher.
     * @return the REF_VOUCHER
     */
    public String getRefVoucher() {
        return (String) getAttributeInternal(REFVOUCHER);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_VOUCHER using the alias name RefVoucher.
     * @param value value to set the REF_VOUCHER
     */
    public void setRefVoucher(String value) {
        setAttributeInternal(REFVOUCHER, value);
    }

    /**
     * Gets the attribute value for SUBMIT using the alias name Submit.
     * @return the SUBMIT
     */
    public String getSubmit() {
        return (String) getAttributeInternal(SUBMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT using the alias name Submit.
     * @param value value to set the SUBMIT
     */
    public void setSubmit(String value) {
        setAttributeInternal(SUBMIT, value);
    }

    /**
     * Gets the attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @return the POST_TO_INT_FACE
     */
    public String getPostToIntFace() {
        return (String) getAttributeInternal(POSTTOINTFACE);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @param value value to set the POST_TO_INT_FACE
     */
    public void setPostToIntFace(String value) {
        setAttributeInternal(POSTTOINTFACE, value);
    }

    /**
     * Gets the attribute value for POST_TO_GL using the alias name PostToGl.
     * @return the POST_TO_GL
     */
    public String getPostToGl() {
        return (String) getAttributeInternal(POSTTOGL);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_GL using the alias name PostToGl.
     * @param value value to set the POST_TO_GL
     */
    public void setPostToGl(String value) {
        setAttributeInternal(POSTTOGL, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for SUBMIT_BY using the alias name SubmitBy.
     * @return the SUBMIT_BY
     */
    public String getSubmitBy() {
        return (String) getAttributeInternal(SUBMITBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT_BY using the alias name SubmitBy.
     * @param value value to set the SUBMIT_BY
     */
    public void setSubmitBy(String value) {
        setAttributeInternal(SUBMITBY, value);
    }

    /**
     * Gets the attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @return the GLVOUCHER_NO
     */
    public String getGlvoucherNo() {
        return (String) getAttributeInternal(GLVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @param value value to set the GLVOUCHER_NO
     */
    public void setGlvoucherNo(String value) {
        setAttributeInternal(GLVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for AR_POSTED using the alias name ArPosted.
     * @return the AR_POSTED
     */
    public String getArPosted() {
        return (String) getAttributeInternal(ARPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for AR_POSTED using the alias name ArPosted.
     * @param value value to set the AR_POSTED
     */
    public void setArPosted(String value) {
        setAttributeInternal(ARPOSTED, value);
    }

    /**
     * Gets the attribute value for SALESPERSONID using the alias name Salespersonid.
     * @return the SALESPERSONID
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESPERSONID using the alias name Salespersonid.
     * @param value value to set the SALESPERSONID
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * Gets the attribute value for PID using the alias name Pid.
     * @return the PID
     */
    public Integer getPid() {
        return (Integer) getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as attribute value for PID using the alias name Pid.
     * @param value value to set the PID
     */
    public void setPid(Integer value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @return the REMARKS_NARR
     */
    public String getRemarksNarr() {
        return (String) getAttributeInternal(REMARKSNARR);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @param value value to set the REMARKS_NARR
     */
    public void setRemarksNarr(String value) {
        setAttributeInternal(REMARKSNARR, value);
    }

    /**
     * Gets the attribute value for FROM_SALE_DATE using the alias name FromSaleDate.
     * @return the FROM_SALE_DATE
     */
    public Date getFromSaleDate() {
        return (Date) getAttributeInternal(FROMSALEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_SALE_DATE using the alias name FromSaleDate.
     * @param value value to set the FROM_SALE_DATE
     */
    public void setFromSaleDate(Date value) {
        setAttributeInternal(FROMSALEDATE, value);
    }

    /**
     * Gets the attribute value for TO_SALE_DATE using the alias name ToSaleDate.
     * @return the TO_SALE_DATE
     */
    public Date getToSaleDate() {
        return (Date) getAttributeInternal(TOSALEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_SALE_DATE using the alias name ToSaleDate.
     * @param value value to set the TO_SALE_DATE
     */
    public void setToSaleDate(Date value) {
        setAttributeInternal(TOSALEDATE, value);
    }

    /**
     * Gets the attribute value for DISCOUNT_TYPE using the alias name DiscountType.
     * @return the DISCOUNT_TYPE
     */
    public String getDiscountType() {
        return (String) getAttributeInternal(DISCOUNTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT_TYPE using the alias name DiscountType.
     * @param value value to set the DISCOUNT_TYPE
     */
    public void setDiscountType(String value) {
        setAttributeInternal(DISCOUNTTYPE, value);
    }

    /**
     * Gets the attribute value for AUDITOR_CHECK using the alias name AuditorCheck.
     * @return the AUDITOR_CHECK
     */
    public String getAuditorCheck() {
        return (String) getAttributeInternal(AUDITORCHECK);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDITOR_CHECK using the alias name AuditorCheck.
     * @param value value to set the AUDITOR_CHECK
     */
    public void setAuditorCheck(String value) {
        setAttributeInternal(AUDITORCHECK, value);
    }

    /**
     * Gets the attribute value for AUDIT_REMARKS using the alias name AuditRemarks.
     * @return the AUDIT_REMARKS
     */
    public String getAuditRemarks() {
        return (String) getAttributeInternal(AUDITREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for AUDIT_REMARKS using the alias name AuditRemarks.
     * @param value value to set the AUDIT_REMARKS
     */
    public void setAuditRemarks(String value) {
        setAttributeInternal(AUDITREMARKS, value);
    }

    /**
     * Gets the attribute value for REF_SALESORDERID using the alias name RefSalesorderid.
     * @return the REF_SALESORDERID
     */
    public String getRefSalesorderid() {
        return (String) getAttributeInternal(REFSALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_SALESORDERID using the alias name RefSalesorderid.
     * @param value value to set the REF_SALESORDERID
     */
    public void setRefSalesorderid(String value) {
        setAttributeInternal(REFSALESORDERID, value);
    }

    /**
     * Gets the attribute value for REF_DOCTYPEID using the alias name RefDoctypeid.
     * @return the REF_DOCTYPEID
     */
    public String getRefDoctypeid() {
        return (String) getAttributeInternal(REFDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_DOCTYPEID using the alias name RefDoctypeid.
     * @param value value to set the REF_DOCTYPEID
     */
    public void setRefDoctypeid(String value) {
        setAttributeInternal(REFDOCTYPEID, value);
    }

    /**
     * Gets the attribute value for REF_VOUCHER_NO using the alias name RefVoucherNo.
     * @return the REF_VOUCHER_NO
     */
    public String getRefVoucherNo() {
        return (String) getAttributeInternal(REFVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_VOUCHER_NO using the alias name RefVoucherNo.
     * @param value value to set the REF_VOUCHER_NO
     */
    public void setRefVoucherNo(String value) {
        setAttributeInternal(REFVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for DOC_DATE using the alias name DocDate.
     * @return the DOC_DATE
     */
    public Date getDocDate() {
        return (Date) getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DATE using the alias name DocDate.
     * @param value value to set the DOC_DATE
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @return the LOC_CURRCODE
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @param value value to set the LOC_CURRCODE
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for FCURR_TOTAL_AMOUNT using the alias name FcurrTotalAmount.
     * @return the FCURR_TOTAL_AMOUNT
     */
    public BigDecimal getFcurrTotalAmount() {
        return (BigDecimal) getAttributeInternal(FCURRTOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_TOTAL_AMOUNT using the alias name FcurrTotalAmount.
     * @param value value to set the FCURR_TOTAL_AMOUNT
     */
    public void setFcurrTotalAmount(BigDecimal value) {
        setAttributeInternal(FCURRTOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for NOTEMASTERSEQ using the alias name Notemasterseq.
     * @return the NOTEMASTERSEQ
     */
    public Integer getNotemasterseq() {
        return (Integer) getAttributeInternal(NOTEMASTERSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTEMASTERSEQ using the alias name Notemasterseq.
     * @param value value to set the NOTEMASTERSEQ
     */
    public void setNotemasterseq(Integer value) {
        setAttributeInternal(NOTEMASTERSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @return the TXT_CUSTOMER_NAME
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @param value value to set the TXT_CUSTOMER_NAME
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @return the TXT_SALES_PERSON_NAME
     */
    public String gettxtSalesPersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @param value value to set the TXT_SALES_PERSON_NAME
     */
    public void settxtSalesPersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ArNoteDetailView.
     */
    public RowIterator getArNoteDetailView() {
        return (RowIterator) getAttributeInternal(ARNOTEDETAILVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllCustomersView.
     */
    public Row getAllCustomersView() {
        return (Row) getAttributeInternal(ALLCUSTOMERSVIEW);
    }

    /**
     * Sets the master-detail link AllCustomersView between this object and <code>value</code>.
     */
    public void setAllCustomersView(Row value) {
        setAttributeInternal(ALLCUSTOMERSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SoSalesPersonsView.
     */
    public Row getSoSalesPersonsView() {
        return (Row) getAttributeInternal(SOSALESPERSONSVIEW);
    }

    /**
     * Sets the master-detail link SoSalesPersonsView between this object and <code>value</code>.
     */
    public void setSoSalesPersonsView(Row value) {
        setAttributeInternal(SOSALESPERSONSVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomersView.
     */
    public RowSet getAccAllCustomersView() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsView.
     */
    public RowSet getAccSoSalesPersonsView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsDefaultVC.
     */
    public RowSet getAccSoSalesPersonsDefaultVC() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSDEFAULTVC);
    }
}

