package erpsolfms.erpsolfmsmodel.erpsolfmsvo;

import erpsolfms.erpsolfmsmodel.erpsolfmsvo.common.ReceiptMasterControlView;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 26 14:13:46 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiptMasterControlViewImpl extends ViewObjectImpl implements ReceiptMasterControlView {
    /**
     * This is the default constructor (do not remove).
     */
    public ReceiptMasterControlViewImpl() {
    }

    public void doSuperviseControlReceipt() {
        
        CallableStatement cs=this.getDBTransaction().createCallableStatement("begin ?:=PKG_SALE_ORDER.FUNC_SUBMIT_SALES_ORDER('"+this.getCurrentRow().getAttribute("ReceiptNo")+"','"+ERPSolGlobClassModel.doGetUserCode()+"'); END;", 1);
        System.out.println("begin ?:=pkg_receipt.func_submit_control_receipt('"+this.getCurrentRow().getAttribute("ReceiptNo")+"'); END;");
        try {
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.executeUpdate();
            this.getCurrentRow().refresh(Row.REFRESH_WITH_DB_FORGET_CHANGES);
            this.getCurrentRow().setAttribute("Submit", "Y");
            if (!cs.getString(1).equals("ERPSOLSUCCESS")) {
//               this.getCurrentRow().setAttribute("Submit", "N");
               this.getDBTransaction().rollback();
                throw new JboException("Unable to supervise due to "+cs.getString(1));
               
           }
            this.getDBTransaction().commit();
        } catch (SQLException e) {
//            this.getCurrentRow().setAttribute("Submit", "N");
            this.getDBTransaction().rollback();
            System.out.println(e.getMessage()+ "this is message");
            throw new JboException("Unable to supervise ");
        }
        finally{
            try {
                cs.close();
            } catch (SQLException e) {
            }
        }
    }    
}

