package erpsolfms.erpsolfmsmodel.erpsolfmsvo;

import erpsolfms.erpsolfmsmodel.erpsolfmseo.ReceiptDetailControlImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 26 14:29:34 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiptDetailControlViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_RECEIPTDETAILCONTROL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ReceiptNo,
        Customerid,
        Salespersonid,
        Pid,
        Amount,
        Lineno,
        TaxAmount,
        CancelAmount,
        FcurrAmount,
        FcurrTaxAmount,
        FcurrCancelAmount,
        Receiptdetailseq,
        txtSalesPersonName,
        Receiptseq,
        txtCustomerName,
        SoSalesPersonsView,
        ReceiptMasterControlView,
        AccSoSalesPersonsView,
        AccAllCustomerSalespersonPID;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RECEIPTNO = AttributesEnum.ReceiptNo.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int PID = AttributesEnum.Pid.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int CANCELAMOUNT = AttributesEnum.CancelAmount.index();
    public static final int FCURRAMOUNT = AttributesEnum.FcurrAmount.index();
    public static final int FCURRTAXAMOUNT = AttributesEnum.FcurrTaxAmount.index();
    public static final int FCURRCANCELAMOUNT = AttributesEnum.FcurrCancelAmount.index();
    public static final int RECEIPTDETAILSEQ = AttributesEnum.Receiptdetailseq.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalesPersonName.index();
    public static final int RECEIPTSEQ = AttributesEnum.Receiptseq.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int SOSALESPERSONSVIEW = AttributesEnum.SoSalesPersonsView.index();
    public static final int RECEIPTMASTERCONTROLVIEW = AttributesEnum.ReceiptMasterControlView.index();
    public static final int ACCSOSALESPERSONSVIEW = AttributesEnum.AccSoSalesPersonsView.index();
    public static final int ACCALLCUSTOMERSALESPERSONPID = AttributesEnum.AccAllCustomerSalespersonPID.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReceiptDetailControlViewRowImpl() {
    }

    /**
     * Gets ReceiptDetailControl entity object.
     * @return the ReceiptDetailControl
     */
    public ReceiptDetailControlImpl getReceiptDetailControl() {
        return (ReceiptDetailControlImpl) getEntity(ENTITY_RECEIPTDETAILCONTROL);
    }

    /**
     * Gets the attribute value for RECEIPT_NO using the alias name ReceiptNo.
     * @return the RECEIPT_NO
     */
    public String getReceiptNo() {
        return (String) getAttributeInternal(RECEIPTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_NO using the alias name ReceiptNo.
     * @param value value to set the RECEIPT_NO
     */
    public void setReceiptNo(String value) {
        setAttributeInternal(RECEIPTNO, value);
    }

    /**
     * Gets the attribute value for CUSTOMERID using the alias name Customerid.
     * @return the CUSTOMERID
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMERID using the alias name Customerid.
     * @param value value to set the CUSTOMERID
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for SALESPERSONID using the alias name Salespersonid.
     * @return the SALESPERSONID
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESPERSONID using the alias name Salespersonid.
     * @param value value to set the SALESPERSONID
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
        getAccAllCustomerSalespersonPID().setNamedWhereClauseParam("P_ADF_CUSTOMERID", getCustomerid());
        getAccAllCustomerSalespersonPID().setNamedWhereClauseParam("P_ADF_SALESPERSONID", value);
        getAccAllCustomerSalespersonPID().executeQuery();
        setPid((Integer)getAccAllCustomerSalespersonPID().first().getAttribute("Id"));
        
    }

    /**
     * Gets the attribute value for PID using the alias name Pid.
     * @return the PID
     */
    public Integer getPid() {
        return (Integer) getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as attribute value for PID using the alias name Pid.
     * @param value value to set the PID
     */
    public void setPid(Integer value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for LINENO using the alias name Lineno.
     * @return the LINENO
     */
    public BigDecimal getLineno() {
        return (BigDecimal) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINENO using the alias name Lineno.
     * @param value value to set the LINENO
     */
    public void setLineno(BigDecimal value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(BigDecimal value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for CANCEL_AMOUNT using the alias name CancelAmount.
     * @return the CANCEL_AMOUNT
     */
    public BigDecimal getCancelAmount() {
        return (BigDecimal) getAttributeInternal(CANCELAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_AMOUNT using the alias name CancelAmount.
     * @param value value to set the CANCEL_AMOUNT
     */
    public void setCancelAmount(BigDecimal value) {
        setAttributeInternal(CANCELAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_AMOUNT using the alias name FcurrAmount.
     * @return the FCURR_AMOUNT
     */
    public BigDecimal getFcurrAmount() {
        return (BigDecimal) getAttributeInternal(FCURRAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_AMOUNT using the alias name FcurrAmount.
     * @param value value to set the FCURR_AMOUNT
     */
    public void setFcurrAmount(BigDecimal value) {
        setAttributeInternal(FCURRAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_TAX_AMOUNT using the alias name FcurrTaxAmount.
     * @return the FCURR_TAX_AMOUNT
     */
    public BigDecimal getFcurrTaxAmount() {
        return (BigDecimal) getAttributeInternal(FCURRTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_TAX_AMOUNT using the alias name FcurrTaxAmount.
     * @param value value to set the FCURR_TAX_AMOUNT
     */
    public void setFcurrTaxAmount(BigDecimal value) {
        setAttributeInternal(FCURRTAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_CANCEL_AMOUNT using the alias name FcurrCancelAmount.
     * @return the FCURR_CANCEL_AMOUNT
     */
    public BigDecimal getFcurrCancelAmount() {
        return (BigDecimal) getAttributeInternal(FCURRCANCELAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_CANCEL_AMOUNT using the alias name FcurrCancelAmount.
     * @param value value to set the FCURR_CANCEL_AMOUNT
     */
    public void setFcurrCancelAmount(BigDecimal value) {
        setAttributeInternal(FCURRCANCELAMOUNT, value);
    }

    /**
     * Gets the attribute value for RECEIPTDETAILSEQ using the alias name Receiptdetailseq.
     * @return the RECEIPTDETAILSEQ
     */
    public Integer getReceiptdetailseq() {
        return (Integer) getAttributeInternal(RECEIPTDETAILSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPTDETAILSEQ using the alias name Receiptdetailseq.
     * @param value value to set the RECEIPTDETAILSEQ
     */
    public void setReceiptdetailseq(Integer value) {
        setAttributeInternal(RECEIPTDETAILSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @return the TXT_SALES_PERSON_NAME
     */
    public String gettxtSalesPersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @param value value to set the TXT_SALES_PERSON_NAME
     */
    public void settxtSalesPersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for RECEIPTSEQ using the alias name Receiptseq.
     * @return the RECEIPTSEQ
     */
    public BigDecimal getReceiptseq() {
        return (BigDecimal) getAttributeInternal(RECEIPTSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPTSEQ using the alias name Receiptseq.
     * @param value value to set the RECEIPTSEQ
     */
    public void setReceiptseq(BigDecimal value) {
        setAttributeInternal(RECEIPTSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @return the TXT_CUSTOMER_NAME
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @param value value to set the TXT_CUSTOMER_NAME
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SoSalesPersonsView.
     */
    public Row getSoSalesPersonsView() {
        return (Row) getAttributeInternal(SOSALESPERSONSVIEW);
    }

    /**
     * Sets the master-detail link SoSalesPersonsView between this object and <code>value</code>.
     */
    public void setSoSalesPersonsView(Row value) {
        setAttributeInternal(SOSALESPERSONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ReceiptMasterControlView.
     */
    public Row getReceiptMasterControlView() {
        return (Row) getAttributeInternal(RECEIPTMASTERCONTROLVIEW);
    }

    /**
     * Sets the master-detail link ReceiptMasterControlView between this object and <code>value</code>.
     */
    public void setReceiptMasterControlView(Row value) {
        setAttributeInternal(RECEIPTMASTERCONTROLVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsView.
     */
    public RowSet getAccSoSalesPersonsView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEW);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomerSalespersonPID.
     */
    public RowSet getAccAllCustomerSalespersonPID() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSALESPERSONPID);
    }

    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getReceiptMasterControlView().getAttribute("Submit").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }    
}

