package erpsolfms.erpsolfmsmodel.erpsolfmsvo;

import erpsolfms.erpsolfmsmodel.erpsolfmseo.ReceiptMasterControlImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 26 14:28:46 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiptMasterControlViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_RECEIPTMASTERCONTROL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ReceiptNo,
        DocTypeId,
        Customerid,
        Companyid,
        Locationid,
        ReceiptDate,
        Createdby,
        Modifiedby,
        CreatedDate,
        ModifiedDate,
        ReceiptMode,
        ReceiptType,
        RefVoucherNo,
        TotalAmount,
        ChequeNo,
        ChequeDate,
        Submit,
        PostToIntFace,
        PostToGl,
        Bankid,
        Branchid,
        Deptid,
        SubmitBy,
        GlvoucherNo,
        ArPosted,
        Remarks,
        RecDate,
        Salespersonid,
        Pid,
        RemarksNarr,
        TaxCode,
        TaxAmount,
        Percent,
        TaxGlcode,
        TaxCcenter,
        Load,
        Rmode,
        DocDate,
        ChequeCancel,
        RefCancelControlReceipt,
        RefCancelReceiptAmount,
        ChqReturnDate,
        IsMigrated,
        MigratedDate,
        CustomerAcNo,
        CustomerAcValidate,
        ExchangeRate,
        LocCurrcode,
        OldReceiptNo,
        VoucherNo,
        VoucherType,
        VoucherCheqNo,
        Supplierid,
        PaymentCodeRef,
        txtCustomerName,
        Receiptseq,
        txtSalesPersonName,
        txtBankBranchName,
        txtSumReceiptAmount,
        ReceiptDetailControlView,
        AllCustomersView,
        SoSalesPersonsView,
        AllBankBranchesView,
        VwAllCustomerQVO,
        AccAllCustomersView,
        AccSoSalesPersonsView,
        AccAllBankBranchesView,
        AccSoSalesPersonsViewDefaultVC,
        AccAllCustomerSalespersonPid,
        AccVWYesNoQVO,
        AccVwAllCustomerQVO,
        AccVWAllBankBranchesQVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RECEIPTNO = AttributesEnum.ReceiptNo.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int RECEIPTDATE = AttributesEnum.ReceiptDate.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int RECEIPTMODE = AttributesEnum.ReceiptMode.index();
    public static final int RECEIPTTYPE = AttributesEnum.ReceiptType.index();
    public static final int REFVOUCHERNO = AttributesEnum.RefVoucherNo.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int CHEQUENO = AttributesEnum.ChequeNo.index();
    public static final int CHEQUEDATE = AttributesEnum.ChequeDate.index();
    public static final int SUBMIT = AttributesEnum.Submit.index();
    public static final int POSTTOINTFACE = AttributesEnum.PostToIntFace.index();
    public static final int POSTTOGL = AttributesEnum.PostToGl.index();
    public static final int BANKID = AttributesEnum.Bankid.index();
    public static final int BRANCHID = AttributesEnum.Branchid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int SUBMITBY = AttributesEnum.SubmitBy.index();
    public static final int GLVOUCHERNO = AttributesEnum.GlvoucherNo.index();
    public static final int ARPOSTED = AttributesEnum.ArPosted.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int RECDATE = AttributesEnum.RecDate.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int PID = AttributesEnum.Pid.index();
    public static final int REMARKSNARR = AttributesEnum.RemarksNarr.index();
    public static final int TAXCODE = AttributesEnum.TaxCode.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int PERCENT = AttributesEnum.Percent.index();
    public static final int TAXGLCODE = AttributesEnum.TaxGlcode.index();
    public static final int TAXCCENTER = AttributesEnum.TaxCcenter.index();
    public static final int LOAD = AttributesEnum.Load.index();
    public static final int RMODE = AttributesEnum.Rmode.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int CHEQUECANCEL = AttributesEnum.ChequeCancel.index();
    public static final int REFCANCELCONTROLRECEIPT = AttributesEnum.RefCancelControlReceipt.index();
    public static final int REFCANCELRECEIPTAMOUNT = AttributesEnum.RefCancelReceiptAmount.index();
    public static final int CHQRETURNDATE = AttributesEnum.ChqReturnDate.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int CUSTOMERACNO = AttributesEnum.CustomerAcNo.index();
    public static final int CUSTOMERACVALIDATE = AttributesEnum.CustomerAcValidate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int OLDRECEIPTNO = AttributesEnum.OldReceiptNo.index();
    public static final int VOUCHERNO = AttributesEnum.VoucherNo.index();
    public static final int VOUCHERTYPE = AttributesEnum.VoucherType.index();
    public static final int VOUCHERCHEQNO = AttributesEnum.VoucherCheqNo.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int PAYMENTCODEREF = AttributesEnum.PaymentCodeRef.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int RECEIPTSEQ = AttributesEnum.Receiptseq.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalesPersonName.index();
    public static final int TXTBANKBRANCHNAME = AttributesEnum.txtBankBranchName.index();
    public static final int TXTSUMRECEIPTAMOUNT = AttributesEnum.txtSumReceiptAmount.index();
    public static final int RECEIPTDETAILCONTROLVIEW = AttributesEnum.ReceiptDetailControlView.index();
    public static final int ALLCUSTOMERSVIEW = AttributesEnum.AllCustomersView.index();
    public static final int SOSALESPERSONSVIEW = AttributesEnum.SoSalesPersonsView.index();
    public static final int ALLBANKBRANCHESVIEW = AttributesEnum.AllBankBranchesView.index();
    public static final int VWALLCUSTOMERQVO = AttributesEnum.VwAllCustomerQVO.index();
    public static final int ACCALLCUSTOMERSVIEW = AttributesEnum.AccAllCustomersView.index();
    public static final int ACCSOSALESPERSONSVIEW = AttributesEnum.AccSoSalesPersonsView.index();
    public static final int ACCALLBANKBRANCHESVIEW = AttributesEnum.AccAllBankBranchesView.index();
    public static final int ACCSOSALESPERSONSVIEWDEFAULTVC = AttributesEnum.AccSoSalesPersonsViewDefaultVC.index();
    public static final int ACCALLCUSTOMERSALESPERSONPID = AttributesEnum.AccAllCustomerSalespersonPid.index();
    public static final int ACCVWYESNOQVO = AttributesEnum.AccVWYesNoQVO.index();
    public static final int ACCVWALLCUSTOMERQVO = AttributesEnum.AccVwAllCustomerQVO.index();
    public static final int ACCVWALLBANKBRANCHESQVO = AttributesEnum.AccVWAllBankBranchesQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReceiptMasterControlViewRowImpl() {
    }

    /**
     * Gets ReceiptMasterControl entity object.
     * @return the ReceiptMasterControl
     */
    public ReceiptMasterControlImpl getReceiptMasterControl() {
        return (ReceiptMasterControlImpl) getEntity(ENTITY_RECEIPTMASTERCONTROL);
    }

    /**
     * Gets the attribute value for RECEIPT_NO using the alias name ReceiptNo.
     * @return the RECEIPT_NO
     */
    public String getReceiptNo() {
        return (String) getAttributeInternal(RECEIPTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_NO using the alias name ReceiptNo.
     * @param value value to set the RECEIPT_NO
     */
    public void setReceiptNo(String value) {
        setAttributeInternal(RECEIPTNO, value);
    }

    /**
     * Gets the attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @return the DOC_TYPE_ID
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @param value value to set the DOC_TYPE_ID
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for CUSTOMERID using the alias name Customerid.
     * @return the CUSTOMERID
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMERID using the alias name Customerid.
     * @param value value to set the CUSTOMERID
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
        try {
            getAccSoSalesPersonsViewDefaultVC().setNamedWhereClauseParam("P_ADF_CUSTOMERID", value);
            getAccSoSalesPersonsViewDefaultVC().executeQuery();
            setSalespersonid((String) getAccSoSalesPersonsViewDefaultVC().first().getAttribute("Salespersonid"));
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for RECEIPT_DATE using the alias name ReceiptDate.
     * @return the RECEIPT_DATE
     */
    public Date getReceiptDate() {
        return (Date) getAttributeInternal(RECEIPTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_DATE using the alias name ReceiptDate.
     * @param value value to set the RECEIPT_DATE
     */
    public void setReceiptDate(Date value) {
        setAttributeInternal(RECEIPTDATE, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for RECEIPT_MODE using the alias name ReceiptMode.
     * @return the RECEIPT_MODE
     */
    public String getReceiptMode() {
        return (String) getAttributeInternal(RECEIPTMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_MODE using the alias name ReceiptMode.
     * @param value value to set the RECEIPT_MODE
     */
    public void setReceiptMode(String value) {
        setAttributeInternal(RECEIPTMODE, value);
    }

    /**
     * Gets the attribute value for RECEIPT_TYPE using the alias name ReceiptType.
     * @return the RECEIPT_TYPE
     */
    public String getReceiptType() {
        return (String) getAttributeInternal(RECEIPTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_TYPE using the alias name ReceiptType.
     * @param value value to set the RECEIPT_TYPE
     */
    public void setReceiptType(String value) {
        setAttributeInternal(RECEIPTTYPE, value);
    }

    /**
     * Gets the attribute value for REF_VOUCHER_NO using the alias name RefVoucherNo.
     * @return the REF_VOUCHER_NO
     */
    public String getRefVoucherNo() {
        return (String) getAttributeInternal(REFVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_VOUCHER_NO using the alias name RefVoucherNo.
     * @param value value to set the REF_VOUCHER_NO
     */
    public void setRefVoucherNo(String value) {
        setAttributeInternal(REFVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for CHEQUE_NO using the alias name ChequeNo.
     * @return the CHEQUE_NO
     */
    public String getChequeNo() {
        return (String) getAttributeInternal(CHEQUENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CHEQUE_NO using the alias name ChequeNo.
     * @param value value to set the CHEQUE_NO
     */
    public void setChequeNo(String value) {
        setAttributeInternal(CHEQUENO, value);
    }

    /**
     * Gets the attribute value for CHEQUE_DATE using the alias name ChequeDate.
     * @return the CHEQUE_DATE
     */
    public Date getChequeDate() {
        return (Date) getAttributeInternal(CHEQUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHEQUE_DATE using the alias name ChequeDate.
     * @param value value to set the CHEQUE_DATE
     */
    public void setChequeDate(Date value) {
        setAttributeInternal(CHEQUEDATE, value);
    }

    /**
     * Gets the attribute value for SUBMIT using the alias name Submit.
     * @return the SUBMIT
     */
    public String getSubmit() {
        return (String) getAttributeInternal(SUBMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT using the alias name Submit.
     * @param value value to set the SUBMIT
     */
    public void setSubmit(String value) {
        setAttributeInternal(SUBMIT, value);
    }

    /**
     * Gets the attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @return the POST_TO_INT_FACE
     */
    public String getPostToIntFace() {
        return (String) getAttributeInternal(POSTTOINTFACE);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @param value value to set the POST_TO_INT_FACE
     */
    public void setPostToIntFace(String value) {
        setAttributeInternal(POSTTOINTFACE, value);
    }

    /**
     * Gets the attribute value for POST_TO_GL using the alias name PostToGl.
     * @return the POST_TO_GL
     */
    public String getPostToGl() {
        return (String) getAttributeInternal(POSTTOGL);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_GL using the alias name PostToGl.
     * @param value value to set the POST_TO_GL
     */
    public void setPostToGl(String value) {
        setAttributeInternal(POSTTOGL, value);
    }

    /**
     * Gets the attribute value for BANKID using the alias name Bankid.
     * @return the BANKID
     */
    public String getBankid() {
        return (String) getAttributeInternal(BANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for BANKID using the alias name Bankid.
     * @param value value to set the BANKID
     */
    public void setBankid(String value) {
        setAttributeInternal(BANKID, value);
    }

    /**
     * Gets the attribute value for BRANCHID using the alias name Branchid.
     * @return the BRANCHID
     */
    public String getBranchid() {
        return (String) getAttributeInternal(BRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCHID using the alias name Branchid.
     * @param value value to set the BRANCHID
     */
    public void setBranchid(String value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**
     * Gets the attribute value for DEPTID using the alias name Deptid.
     * @return the DEPTID
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTID using the alias name Deptid.
     * @param value value to set the DEPTID
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for SUBMIT_BY using the alias name SubmitBy.
     * @return the SUBMIT_BY
     */
    public String getSubmitBy() {
        return (String) getAttributeInternal(SUBMITBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT_BY using the alias name SubmitBy.
     * @param value value to set the SUBMIT_BY
     */
    public void setSubmitBy(String value) {
        setAttributeInternal(SUBMITBY, value);
    }

    /**
     * Gets the attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @return the GLVOUCHER_NO
     */
    public String getGlvoucherNo() {
        return (String) getAttributeInternal(GLVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @param value value to set the GLVOUCHER_NO
     */
    public void setGlvoucherNo(String value) {
        setAttributeInternal(GLVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for AR_POSTED using the alias name ArPosted.
     * @return the AR_POSTED
     */
    public String getArPosted() {
        return (String) getAttributeInternal(ARPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for AR_POSTED using the alias name ArPosted.
     * @param value value to set the AR_POSTED
     */
    public void setArPosted(String value) {
        setAttributeInternal(ARPOSTED, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REC_DATE using the alias name RecDate.
     * @return the REC_DATE
     */
    public Date getRecDate() {
        return (Date) getAttributeInternal(RECDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REC_DATE using the alias name RecDate.
     * @param value value to set the REC_DATE
     */
    public void setRecDate(Date value) {
        setAttributeInternal(RECDATE, value);
    }

    /**
     * Gets the attribute value for SALESPERSONID using the alias name Salespersonid.
     * @return the SALESPERSONID
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESPERSONID using the alias name Salespersonid.
     * @param value value to set the SALESPERSONID
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
        try {
            getAccAllCustomerSalespersonPid().setNamedWhereClauseParam("P_ADF_CUSTOMERID", getCustomerid());
            getAccAllCustomerSalespersonPid().setNamedWhereClauseParam("P_ADF_SALESPERSONID", value);
            getAccAllCustomerSalespersonPid().executeQuery();
            setPid((Integer) getAccAllCustomerSalespersonPid().first().getAttribute("Id"));
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }      
    }

    /**
     * Gets the attribute value for PID using the alias name Pid.
     * @return the PID
     */
    public Integer getPid() {
        return (Integer) getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as attribute value for PID using the alias name Pid.
     * @param value value to set the PID
     */
    public void setPid(Integer value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @return the REMARKS_NARR
     */
    public String getRemarksNarr() {
        return (String) getAttributeInternal(REMARKSNARR);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @param value value to set the REMARKS_NARR
     */
    public void setRemarksNarr(String value) {
        setAttributeInternal(REMARKSNARR, value);
    }

    /**
     * Gets the attribute value for TAX_CODE using the alias name TaxCode.
     * @return the TAX_CODE
     */
    public BigDecimal getTaxCode() {
        return (BigDecimal) getAttributeInternal(TAXCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CODE using the alias name TaxCode.
     * @param value value to set the TAX_CODE
     */
    public void setTaxCode(BigDecimal value) {
        setAttributeInternal(TAXCODE, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public BigDecimal getTaxAmount() {
        return (BigDecimal) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(BigDecimal value) {
        setAttributeInternal(TAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for PERCENT using the alias name Percent.
     * @return the PERCENT
     */
    public BigDecimal getPercent() {
        return (BigDecimal) getAttributeInternal(PERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PERCENT using the alias name Percent.
     * @param value value to set the PERCENT
     */
    public void setPercent(BigDecimal value) {
        setAttributeInternal(PERCENT, value);
    }

    /**
     * Gets the attribute value for TAX_GLCODE using the alias name TaxGlcode.
     * @return the TAX_GLCODE
     */
    public String getTaxGlcode() {
        return (String) getAttributeInternal(TAXGLCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_GLCODE using the alias name TaxGlcode.
     * @param value value to set the TAX_GLCODE
     */
    public void setTaxGlcode(String value) {
        setAttributeInternal(TAXGLCODE, value);
    }

    /**
     * Gets the attribute value for TAX_CCENTER using the alias name TaxCcenter.
     * @return the TAX_CCENTER
     */
    public String getTaxCcenter() {
        return (String) getAttributeInternal(TAXCCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_CCENTER using the alias name TaxCcenter.
     * @param value value to set the TAX_CCENTER
     */
    public void setTaxCcenter(String value) {
        setAttributeInternal(TAXCCENTER, value);
    }

    /**
     * Gets the attribute value for LOAD using the alias name Load.
     * @return the LOAD
     */
    public String getLoad() {
        return (String) getAttributeInternal(LOAD);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAD using the alias name Load.
     * @param value value to set the LOAD
     */
    public void setLoad(String value) {
        setAttributeInternal(LOAD, value);
    }

    /**
     * Gets the attribute value for RMODE using the alias name Rmode.
     * @return the RMODE
     */
    public String getRmode() {
        return (String) getAttributeInternal(RMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RMODE using the alias name Rmode.
     * @param value value to set the RMODE
     */
    public void setRmode(String value) {
        setAttributeInternal(RMODE, value);
    }

    /**
     * Gets the attribute value for DOC_DATE using the alias name DocDate.
     * @return the DOC_DATE
     */
    public Date getDocDate() {
        return (Date) getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DATE using the alias name DocDate.
     * @param value value to set the DOC_DATE
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for CHEQUE_CANCEL using the alias name ChequeCancel.
     * @return the CHEQUE_CANCEL
     */
    public String getChequeCancel() {
        return (String) getAttributeInternal(CHEQUECANCEL);
    }

    /**
     * Sets <code>value</code> as attribute value for CHEQUE_CANCEL using the alias name ChequeCancel.
     * @param value value to set the CHEQUE_CANCEL
     */
    public void setChequeCancel(String value) {
        setAttributeInternal(CHEQUECANCEL, value);
    }

    /**
     * Gets the attribute value for REF_CANCEL_CONTROL_RECEIPT using the alias name RefCancelControlReceipt.
     * @return the REF_CANCEL_CONTROL_RECEIPT
     */
    public String getRefCancelControlReceipt() {
        return (String) getAttributeInternal(REFCANCELCONTROLRECEIPT);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_CANCEL_CONTROL_RECEIPT using the alias name RefCancelControlReceipt.
     * @param value value to set the REF_CANCEL_CONTROL_RECEIPT
     */
    public void setRefCancelControlReceipt(String value) {
        setAttributeInternal(REFCANCELCONTROLRECEIPT, value);
    }

    /**
     * Gets the attribute value for REF_CANCEL_RECEIPT_AMOUNT using the alias name RefCancelReceiptAmount.
     * @return the REF_CANCEL_RECEIPT_AMOUNT
     */
    public BigDecimal getRefCancelReceiptAmount() {
        return (BigDecimal) getAttributeInternal(REFCANCELRECEIPTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_CANCEL_RECEIPT_AMOUNT using the alias name RefCancelReceiptAmount.
     * @param value value to set the REF_CANCEL_RECEIPT_AMOUNT
     */
    public void setRefCancelReceiptAmount(BigDecimal value) {
        setAttributeInternal(REFCANCELRECEIPTAMOUNT, value);
    }

    /**
     * Gets the attribute value for CHQ_RETURN_DATE using the alias name ChqReturnDate.
     * @return the CHQ_RETURN_DATE
     */
    public Date getChqReturnDate() {
        return (Date) getAttributeInternal(CHQRETURNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHQ_RETURN_DATE using the alias name ChqReturnDate.
     * @param value value to set the CHQ_RETURN_DATE
     */
    public void setChqReturnDate(Date value) {
        setAttributeInternal(CHQRETURNDATE, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_AC_NO using the alias name CustomerAcNo.
     * @return the CUSTOMER_AC_NO
     */
    public String getCustomerAcNo() {
        return (String) getAttributeInternal(CUSTOMERACNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_AC_NO using the alias name CustomerAcNo.
     * @param value value to set the CUSTOMER_AC_NO
     */
    public void setCustomerAcNo(String value) {
        setAttributeInternal(CUSTOMERACNO, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_AC_VALIDATE using the alias name CustomerAcValidate.
     * @return the CUSTOMER_AC_VALIDATE
     */
    public String getCustomerAcValidate() {
        return (String) getAttributeInternal(CUSTOMERACVALIDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_AC_VALIDATE using the alias name CustomerAcValidate.
     * @param value value to set the CUSTOMER_AC_VALIDATE
     */
    public void setCustomerAcValidate(String value) {
        setAttributeInternal(CUSTOMERACVALIDATE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @return the LOC_CURRCODE
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @param value value to set the LOC_CURRCODE
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for OLD_RECEIPT_NO using the alias name OldReceiptNo.
     * @return the OLD_RECEIPT_NO
     */
    public String getOldReceiptNo() {
        return (String) getAttributeInternal(OLDRECEIPTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_RECEIPT_NO using the alias name OldReceiptNo.
     * @param value value to set the OLD_RECEIPT_NO
     */
    public void setOldReceiptNo(String value) {
        setAttributeInternal(OLDRECEIPTNO, value);
    }

    /**
     * Gets the attribute value for VOUCHER_NO using the alias name VoucherNo.
     * @return the VOUCHER_NO
     */
    public String getVoucherNo() {
        return (String) getAttributeInternal(VOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_NO using the alias name VoucherNo.
     * @param value value to set the VOUCHER_NO
     */
    public void setVoucherNo(String value) {
        setAttributeInternal(VOUCHERNO, value);
    }

    /**
     * Gets the attribute value for VOUCHER_TYPE using the alias name VoucherType.
     * @return the VOUCHER_TYPE
     */
    public String getVoucherType() {
        return (String) getAttributeInternal(VOUCHERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_TYPE using the alias name VoucherType.
     * @param value value to set the VOUCHER_TYPE
     */
    public void setVoucherType(String value) {
        setAttributeInternal(VOUCHERTYPE, value);
    }

    /**
     * Gets the attribute value for VOUCHER_CHEQ_NO using the alias name VoucherCheqNo.
     * @return the VOUCHER_CHEQ_NO
     */
    public String getVoucherCheqNo() {
        return (String) getAttributeInternal(VOUCHERCHEQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_CHEQ_NO using the alias name VoucherCheqNo.
     * @param value value to set the VOUCHER_CHEQ_NO
     */
    public void setVoucherCheqNo(String value) {
        setAttributeInternal(VOUCHERCHEQNO, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for PAYMENT_CODE_REF using the alias name PaymentCodeRef.
     * @return the PAYMENT_CODE_REF
     */
    public String getPaymentCodeRef() {
        return (String) getAttributeInternal(PAYMENTCODEREF);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_CODE_REF using the alias name PaymentCodeRef.
     * @param value value to set the PAYMENT_CODE_REF
     */
    public void setPaymentCodeRef(String value) {
        setAttributeInternal(PAYMENTCODEREF, value);
    }

    /**
     * Gets the attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @return the TXT_CUSTOMER_NAME
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @param value value to set the TXT_CUSTOMER_NAME
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for RECEIPTSEQ using the alias name Receiptseq.
     * @return the RECEIPTSEQ
     */
    public Integer getReceiptseq() {
        return (Integer) getAttributeInternal(RECEIPTSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPTSEQ using the alias name Receiptseq.
     * @param value value to set the RECEIPTSEQ
     */
    public void setReceiptseq(Integer value) {
        setAttributeInternal(RECEIPTSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @return the TXT_SALES_PERSON_NAME
     */
    public String gettxtSalesPersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @param value value to set the TXT_SALES_PERSON_NAME
     */
    public void settxtSalesPersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_BANK_BRANCH_NAME using the alias name txtBankBranchName.
     * @return the TXT_BANK_BRANCH_NAME
     */
    public String gettxtBankBranchName() {
        return (String) getAttributeInternal(TXTBANKBRANCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_BANK_BRANCH_NAME using the alias name txtBankBranchName.
     * @param value value to set the TXT_BANK_BRANCH_NAME
     */
    public void settxtBankBranchName(String value) {
        setAttributeInternal(TXTBANKBRANCHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSumReceiptAmount.
     * @return the txtSumReceiptAmount
     */
    public BigDecimal gettxtSumReceiptAmount() {
        return (BigDecimal) getAttributeInternal(TXTSUMRECEIPTAMOUNT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ReceiptDetailControlView.
     */
    public RowIterator getReceiptDetailControlView() {
        return (RowIterator) getAttributeInternal(RECEIPTDETAILCONTROLVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllCustomersView.
     */
    public Row getAllCustomersView() {
        return (Row) getAttributeInternal(ALLCUSTOMERSVIEW);
    }

    /**
     * Sets the master-detail link AllCustomersView between this object and <code>value</code>.
     */
    public void setAllCustomersView(Row value) {
        setAttributeInternal(ALLCUSTOMERSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SoSalesPersonsView.
     */
    public Row getSoSalesPersonsView() {
        return (Row) getAttributeInternal(SOSALESPERSONSVIEW);
    }

    /**
     * Sets the master-detail link SoSalesPersonsView between this object and <code>value</code>.
     */
    public void setSoSalesPersonsView(Row value) {
        setAttributeInternal(SOSALESPERSONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllBankBranchesView.
     */
    public Row getAllBankBranchesView() {
        return (Row) getAttributeInternal(ALLBANKBRANCHESVIEW);
    }

    /**
     * Sets the master-detail link AllBankBranchesView between this object and <code>value</code>.
     */
    public void setAllBankBranchesView(Row value) {
        setAttributeInternal(ALLBANKBRANCHESVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link VwAllCustomerQVO.
     */
    public Row getVwAllCustomerQVO() {
        return (Row) getAttributeInternal(VWALLCUSTOMERQVO);
    }

    /**
     * Sets the master-detail link VwAllCustomerQVO between this object and <code>value</code>.
     */
    public void setVwAllCustomerQVO(Row value) {
        setAttributeInternal(VWALLCUSTOMERQVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomersView.
     */
    public RowSet getAccAllCustomersView() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsView.
     */
    public RowSet getAccSoSalesPersonsView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllBankBranchesView.
     */
    public RowSet getAccAllBankBranchesView() {
        return (RowSet) getAttributeInternal(ACCALLBANKBRANCHESVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsViewDefaultVC.
     */
    public RowSet getAccSoSalesPersonsViewDefaultVC() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEWDEFAULTVC);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomerSalespersonPid.
     */
    public RowSet getAccAllCustomerSalespersonPid() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSALESPERSONPID);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWYesNoQVO.
     */
    public RowSet getAccVWYesNoQVO() {
        return (RowSet) getAttributeInternal(ACCVWYESNOQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwAllCustomerQVO.
     */
    public RowSet getAccVwAllCustomerQVO() {
        return (RowSet) getAttributeInternal(ACCVWALLCUSTOMERQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWAllBankBranchesQVO.
     */
    public RowSet getAccVWAllBankBranchesQVO() {
        return (RowSet) getAttributeInternal(ACCVWALLBANKBRANCHESQVO);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getSubmit().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

