package erpsolfms.erpsolfmsmodel.erpsolfmsqvo;

import erpsolfms.erpsolfmsmodel.erpsolfmsqvo.common.VwGLFinanceReportQVO;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import java.sql.CallableStatement;

import java.sql.SQLException;

import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 24 22:07:01 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwGLFinanceReportQVOImpl extends ViewObjectImpl implements VwGLFinanceReportQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public VwGLFinanceReportQVOImpl() {
    }
    public void doExecuteAgingProcedure() {
//Locationid        
        System.out.println("begin ?:=pkg_ar_note.func_run_dealer_Aging('"+this.getCurrentRow().getAttribute("Regionid")+"','"+this.getCurrentRow().getAttribute("Locationid")+"','"+this.getCurrentRow().getAttribute("Companyid")+"',to_date('"+this.first().getAttribute("txtFromDate")+"','yyyy-mm-dd')); END;");
        CallableStatement cs=this.getDBTransaction().createCallableStatement("begin ?:=pkg_ar_note.func_run_dealer_Aging('"+this.getCurrentRow().getAttribute("Regionid")+"','"+this.getCurrentRow().getAttribute("Locationid")+"','"+this.getCurrentRow().getAttribute("Companyid")+"',to_date('"+this.first().getAttribute("txtFromDate")+"','yyyy-mm-dd')); END;", 1);
        try {
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.executeUpdate();
            
            if (!cs.getString(1).equals("ERPSOLSUCCESS")) {
        //               this.getCurrentRow().setAttribute("Submit", "N");
               this.getDBTransaction().commit();
                throw new JboException("Unable to supervise due to "+cs.getString(1));
           }
            this.getDBTransaction().commit();
        } catch (SQLException e) {
        //            this.getCurrentRow().setAttribute("Submit", "N");
            this.getDBTransaction().commit();
            System.out.println(e.getMessage()+ "this is message");
            throw new JboException("Unable to supervise ");
        }
        finally{
            try {
                cs.close();
            } catch (SQLException e) {
            }
        }

    }
    public void doSetERPSolReportDefault() {
        ViewObject vo=getApplicationModule().findViewObject("QvoLoc");
        if (vo!=null) {
            vo.remove();
       }
        vo=getApplicationModule().createViewObjectFromQueryStmt("QvoLoc", "select locationid, location_description from all_locations where locationid='"+ERPSolGlobClassModel.doGetUserLocationCode()+"'");
        vo.executeQuery();;
        this.first().setAttribute("Locationid", vo.first().getAttribute(0));
        this.first().setAttribute("txtLocationName", vo.first().getAttribute(1));
        this.first().setAttribute("Companyid", ERPSolGlobClassModel.doGetUserCompanyCode());
        vo.remove();
    }
}

