package erpsolfms.erpsolfmsmodel.erpsolfmsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 07 14:24:19 PKT 2021
// ---------------------------------------------------------------------
public interface ArNoteMasterView extends ViewObject {
    void doSuperviseARNoteMaster();
}

