package erpsolfms.erpsolfmsmodel.erpsolfmsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 26 14:27:30 PKT 2021
// ---------------------------------------------------------------------
public interface ReceiptMasterControlView extends ViewObject {
    void doSuperviseControlReceipt();
}

