package erpsolfms.erpsolfmsmodel.erpsolfmsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 24 22:16:31 PKT 2021
// ---------------------------------------------------------------------
public interface VwGLFinanceReportQVO extends ViewObject {
    void doExecuteAgingProcedure();

    void doSetERPSolReportDefault();

    void doUnSubmitARRecord();
}

